"""Catalogo declarativo de regras verbetograficas usadas pelo motor formal."""

from __future__ import annotations

DIVISOES = [
    "Conformatica",
    "Fatuistica",
    "Detalhismo",
    "Perfilologia",
    "Argumentologia",
    "Acabativa",
]

DIVISAO_ALIASES = {
    "conformática": "Conformatica",
    "conformatica": "Conformatica",
    "fatuística": "Fatuistica",
    "fatuistica": "Fatuistica",
    "detalhismo": "Detalhismo",
    "perfilologia": "Perfilologia",
    "perfilogia": "Perfilologia",
    "argumentologia": "Argumentologia",
    "acabativa": "Acabativa",
}

SECOES_FIXAS = [
    "Definologia",
    "Sinonimologia",
    "Antonimologia",
    "Remissiologia",
    "Frase Enfatica",
    "Questionologia",
]

SECOES = {
    "Definologia": {"div": "Conformatica", "ordem": 1, "min": None, "max": 7, "enum": "horizontal"},
    "Tematologia": {"div": "Conformatica", "ordem": 2},
    "Etimologia": {"div": "Conformatica", "ordem": 3},
    "Sinonimologia": {"div": "Conformatica", "ordem": 4, "min": 2, "max": 10, "enum": "horizontal_numerada"},
    "Cognatologia": {"div": "Conformatica", "ordem": 5, "min": 3, "max": 10, "enum": "horizontal"},
    "Neologia": {"div": "Conformatica", "ordem": 6, "min": 2, "max": 4, "enum": "horizontal"},
    "Antonimologia": {"div": "Conformatica", "ordem": 7, "min": 2, "max": 10, "enum": "horizontal_numerada"},
    "Estrangeirismologia": {"div": "Conformatica", "ordem": 8, "max": 7, "enum": "horizontal"},
    "Atributologia": {"div": "Conformatica", "ordem": 9},
    "Megapensenologia": {"div": "Conformatica", "ordem": 10},
    "Coloquiologia": {"div": "Conformatica", "ordem": 11},
    "Citaciologia": {"div": "Conformatica", "ordem": 12},
    "Proverbiologia": {"div": "Conformatica", "ordem": 13},
    "Ortopensatologia": {"div": "Conformatica", "ordem": 14},
    "Arcaisticologia": {"div": "Conformatica", "ordem": 15, "enum": "horizontal"},
    "Unidade": {"div": "Conformatica", "ordem": 16},
    "Seciologia": {"div": "Conformatica", "ordem": 17},
    "Pensenologia": {"div": "Fatuistica", "ordem": 1, "enum": "horizontal"},
    "Fatologia": {"div": "Fatuistica", "ordem": 2, "max": 20, "enum": "linhas"},
    "Parafatologia": {"div": "Fatuistica", "ordem": 3, "max": 20, "enum": "linhas"},
    "Sinergismologia": {"div": "Detalhismo", "ordem": 1, "max": 7, "enum": "horizontal"},
    "Principiologia": {"div": "Detalhismo", "ordem": 2, "max": 7, "enum": "horizontal"},
    "Codigologia": {"div": "Detalhismo", "ordem": 3, "max": 7, "enum": "horizontal"},
    "Teoriologia": {"div": "Detalhismo", "ordem": 4, "max": 7, "enum": "horizontal"},
    "Tecnologia": {"div": "Detalhismo", "ordem": 5, "max": 7, "enum": "horizontal"},
    "Voluntariologia": {"div": "Detalhismo", "ordem": 6, "max": 7, "enum": "horizontal"},
    "Laboratoriologia": {"div": "Detalhismo", "ordem": 7, "max": 7, "enum": "horizontal"},
    "Colegiologia": {"div": "Detalhismo", "ordem": 8, "max": 7, "enum": "horizontal"},
    "Efeitologia": {"div": "Detalhismo", "ordem": 9, "max": 7, "enum": "horizontal"},
    "Neossinapsologia": {"div": "Detalhismo", "ordem": 10, "max": 7, "enum": "horizontal"},
    "Ciclologia": {"div": "Detalhismo", "ordem": 11, "max": 7, "enum": "horizontal"},
    "Enumerologia": {"div": "Detalhismo", "ordem": 12, "max": 7, "enum": "horizontal", "exact": 7, "always_max": True},
    "Binomiologia": {"div": "Detalhismo", "ordem": 13, "max": 7, "enum": "horizontal"},
    "Interaciologia": {"div": "Detalhismo", "ordem": 14, "max": 7, "enum": "horizontal"},
    "Crescendologia": {"div": "Detalhismo", "ordem": 15, "max": 7, "enum": "horizontal"},
    "Trinomiologia": {"div": "Detalhismo", "ordem": 16, "max": 7, "enum": "horizontal"},
    "Polinomiologia": {"div": "Detalhismo", "ordem": 17, "max": 7, "enum": "horizontal"},
    "Antagonismologia": {"div": "Detalhismo", "ordem": 18, "max": 7, "enum": "horizontal"},
    "Paradoxologia": {"div": "Detalhismo", "ordem": 19, "max": 7, "enum": "horizontal"},
    "Politicologia": {"div": "Detalhismo", "ordem": 20, "max": 7, "enum": "horizontal"},
    "Legislogia": {"div": "Detalhismo", "ordem": 21, "max": 7, "enum": "horizontal"},
    "Filiologia": {"div": "Detalhismo", "ordem": 22, "max": 7, "enum": "horizontal"},
    "Fobiologia": {"div": "Detalhismo", "ordem": 23, "max": 7, "enum": "horizontal"},
    "Sindromologia": {"div": "Detalhismo", "ordem": 24, "max": 7, "enum": "horizontal"},
    "Maniologia": {"div": "Detalhismo", "ordem": 25, "max": 7, "enum": "horizontal"},
    "Mitologia": {"div": "Detalhismo", "ordem": 26, "max": 7, "enum": "horizontal"},
    "Holotecologia": {"div": "Detalhismo", "ordem": 27, "max": 7, "enum": "horizontal"},
    "Interdisciplinologia": {"div": "Detalhismo", "ordem": 28, "max": 10, "enum": "horizontal"},
    "Elencologia": {"div": "Perfilologia", "ordem": 1, "enum": "horizontal"},
    "Masculinologia": {"div": "Perfilologia", "ordem": 2, "enum": "horizontal"},
    "Femininologia": {"div": "Perfilologia", "ordem": 3, "enum": "horizontal"},
    "Hominologia": {"div": "Perfilologia", "ordem": 4, "max": 7, "enum": "horizontal"},
    "Exemplologia": {"div": "Argumentologia", "ordem": 1, "min": 2, "enum": "horizontal"},
    "Culturologia": {"div": "Argumentologia", "ordem": 2, "enum": "horizontal"},
    "Taxologia": {"div": "Argumentologia", "ordem": 3, "max": 100, "enum": "vertical_numerada"},
    "Caracterologia": {"div": "Argumentologia", "ordem": 4, "enum": "vertical_numerada"},
    "Tipologia": {"div": "Argumentologia", "ordem": 5, "enum": "vertical_numerada"},
    "Terapeuticologia": {"div": "Argumentologia", "ordem": 6, "enum": "horizontal"},
    "Tabelologia": {"div": "Argumentologia", "ordem": 7, "enum": "vertical_numerada"},
    "Remissiologia": {"div": "Acabativa", "ordem": 1, "max": 10, "enum": "vertical_numerada", "totais": {7, 10, 12, 15}},
    "Questionologia": {"div": "Acabativa", "ordem": 3},
    "Filmografia Especifica": {"div": "Acabativa", "ordem": 4},
    "Bibliografia Especifica": {"div": "Acabativa", "ordem": 5, "max": 10, "enum": "vertical_numerada"},
}

MARCA_EXCELENCIA = {"paginas": 3, "maximos": 5, "logias": 25}

PARASITAS = [
    "um",
    "uma",
    "uns",
    "umas",
    "num",
    "numa",
    "nuns",
    "numas",
    "meu",
    "minha",
    "meus",
    "minhas",
    "nosso",
    "nossa",
    "nossos",
    "nossas",
    "seu",
    "sua",
    "seus",
    "suas",
    "teu",
    "tua",
    "teus",
    "tuas",
]
